### ISSUE TITLE
development for laravel 8

### ISSUE THREAD

**Issue by cloner311z** [arfar-x/artisan-api#1]
hello please develop this package for laravel 8

**Comment by arfar-x** [comment]
Dear @cloner311z ,
As Laravel v8.* might have infrastructural changes and all new Laravel projects start with the latest version, there is no need to publish for an older version. Thus, Laravel v8.* uses PHP v7.3 & v8.1, and this package is provided on top PHP v8.0.3. So it is a good way to prevent incompatible collisions with older ones.
Thanks for your consideration.
